### ISSUE TITLE
Deadminned admins still have access

### ISSUE THREAD

**Issue by d3athrow** [tgstation/tgstation13.org#35]
Deadminned myself and it reflects in the database and on the admins page http://ss13.moe/index.php/admins but the rapsheet frontend claims i'm still host and allows me access.
![img](http://ss13.moe/uploads/2017-12-17_09-47-18.png)

**Comment by MrStonedOne** [comment]
It doesn't into db admins so the only admin rank it cares about is the one in the player table for `lastadminrank`.

**Comment by MrStonedOne** [comment]
We solved this by doing this: https://github.com/tgstation/tgstation/pull/8854/commits/5b2221cd4f8a377100f308f22b96cb372db4c512

**Comment by d3athrow** [comment]
Alright thanks.
