### ISSUE TITLE
Fetching player details fails due to new database schema

### ISSUE THREAD

**Issue by Cyprex** [tgstation/tgstation13.org#50]
When trying to open a players detail page like: https://tgstation13.org/tgdb/playerdetails.php?ckey=Booktower a blank page is returned. Inspecting the response via the developer console shows that the request fails with a 500 Internal Server Error response code. The response is empty, firefox shows a blank page instead of an error message.

If adminobservers have insufficient permissions an error message indicating that should be returned. Additonally, a 500 internal server error response should display an error page, I'm guessing browsers use their own if none is supplied? Currently it responds the full response header followed by a few newlines.

**Comment by Jordie0608** [comment]
This isn't related to permissions, the page just isn't being served up. The playerdetails and ban pages have yet to be updated for the recent changes to the database schema, they are non-functional for everyone.

**Comment by Cyprex** [comment]
I believe this has been fixed.
