### ISSUE TITLE
Riding Janicart after fireman carrying doesn't reset offhand status

### ISSUE THREAD

**Issue by Ouroborus113** [tgstation/tgstation13.org#53]
While fireman carrying a body, I jumped on a janicart to move a bit faster. After getting off of it, I was unable to interact with the medbay fridge with my offhand, with it saying the fridge refuses to accept the offhand.

As per my ahelp reply
'Namely, you may want to note that /obj/item/riding_offhand wasn't removed when you left your janicart.'

**Comment by Jordie0608** [comment]
Wrong repo, this is for the website. You want https://github.com/tgstation/tgstation
