### ISSUE TITLE
Small error with borgs and APC battery (APC won't load)

### ISSUE THREAD

**Issue by Nerolostshor** [tgstation/tgstation13.org#54]
Hello, 

i found an issue when i was Building a BSA room with the APC behind armory . (room added to plan normaly & power conduit with power).

By using the borg circuit fabricator i builded a basic battery for an APC But it just won't load.
After getting a human to change the battery for a blue space one (fabricated version from science)
it began to function normaly.

That is all if you need futher information please contact me. I'm trying to see if the error will repeat itself.

**Comment by Jordie0608** [comment]
Wrong repo, this is for the website. You want https://github.com/tgstation/tgstation
