### ISSUE TITLE
Landing page redesign

### ISSUE THREAD

**Issue by mozi-h** [tgstation/tgstation13.org#70]
I'd like to pitch my design before committing to coding it.
Please do let me know of things that need changing! (or if you're against this as a whole)

Notes:
- Intro-block "What is Space Station 13?" moved to top (for newbies) and made dismissible (for veterans).
- Background animated ([demo](https://mozi-h.de/demo/space-bg/)), respects `prefers-reduced-motion`
- Image with open dropdown [here](https://user-images.githubusercontent.com/19172408/132551752-b2931fc6-1ad5-43a8-8421-0eeae09dccbc.png)

<img width="1440" alt="tgstation redesign" src="https://user-images.githubusercontent.com/19172408/132552345-9c8dd86e-4570-451c-8cc6-9315cb01264f.png">

**Comment by mozi-h** [comment]
Sorry for the ping @optimumtact, but could you give a quick 👍 or 👎?

**Comment by optimumtact** [comment]
@mozi-h I don't control the website, you want @MrStonedOne

**Comment by optimumtact** [comment]
also, does it require javascript? looks cool though

**Comment by mozi-h** [comment]
The navbar dropdown will require javascript.
I'm also not too sure how #68 affects the start page, but should be a simple replace of the server boxes, judging by the name.

**Comment by tralezab** [comment]
donation banner at the bottom is a bad idea, the rest is pretty sweet

**Comment by MrStonedOne** [comment]
68 is already live, i was asked to put the code up for it to the github so somebody could just use it. I haven't been all that great on keeping the github up to date given how much easier its been testing and deploying changes when i can do them at the save time by editing production directly. =P

**Comment by MrStonedOne** [comment]
also, everybody said they liked this design,
